FROM node:22-alpine

WORKDIR /app

COPY package*.json ./
# USER node
RUN npm install

COPY . .

RUN chown -R node:node /app

EXPOSE 9000

# CMD ["sh", "-c", "npm run dev -- --host 0.0.0.0"]
# CMD [ "sh" ]